package Negocio;
import ValueObjects.EnemigoVO;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConjuntoInvasor.java
//  @ Date : 05/11/2018
//  @ Author : 
//
//




public class ConjuntoInvasor {
	int i,j;
	
	Enemigo[] ci;
	boolean sentido;
	
	public ConjuntoInvasor (int x, int y) {//20 64
		
		sentido=true;
		ci = new Enemigo[15];
		
		for(i=0;i<15;i++){
			
			if(i == 0){
				
				ci[i] = new Enemigo(x,y);
				x+=80;
				
			}
				
			if(i >= 1 && i < 5) {
			
				ci[i] = new Enemigo(x,y);
				x+=80;
				
			}
			
			if(i==5)
				x=20;
			
			if(i >= 5 && i < 10) {
			
				ci[i] = new Enemigo(x,y+80);
				x+=80;
				
			}
			
			if(i==10)
				x=20;
			
			if(i >= 10){
			
				ci[i] = new Enemigo(x,y+160);
				x+=80;
				
			}
			
		}
	}
	
	public boolean isSentido() {
		return sentido;
	}

	public void setSentido(boolean sentido) {
		this.sentido = sentido;
	}

	public EnemigoVO[] moverDer() {
		EnemigoVO[] enem = new EnemigoVO[15];
		for(i=0;i<15;i++) {
			ci[i].moverDer();
			enem[i] = new EnemigoVO();		
			enem[i].setX(ci[i].getX());
			enem[i].setY(ci[i].getY());
		}
		return enem;
	}
	
	public EnemigoVO[] moverIzq() {
		EnemigoVO[] enem = new EnemigoVO[15];
		for(i=0;i<15;i++) {
			ci[i].moverIzq();
			enem[i] = new EnemigoVO();		
			enem[i].setX(ci[i].getX());
			enem[i].setY(ci[i].getY());
		}
		return enem;
	}
	
	public EnemigoVO[] bajar() {
		EnemigoVO[] enem = new EnemigoVO[15];
		for(i=0;i<15;i++) {
			ci[i].bajar();
			enem[i] = new EnemigoVO();		
			enem[i].setX(ci[i].getX());
			enem[i].setY(ci[i].getY());
		}
		return enem;
	}
	
	public Enemigo[] getCi() {
		return ci;
	}
	
	public boolean isEmpty() {
		
		boolean empty = true;
		
		for(i=0 ; empty==true && i<15 ; i++) {
			if(ci[i].isEstado()) {
				empty=false;
			}
		}
		return empty;
	}
}
