package Negocio;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Disparo.java
//  @ Date : 05/11/2018
//  @ Author : 
//
//




public class Disparo {
	
	private int y;
	private int x;
	
	public Disparo(int x, int y) {
		this.y = y;
		this.x = x;
	}

	public boolean detectarColisiones(int x, int y, boolean estado) {
		if(this.y>=y&&this.y<=y+64&&estado!=false)
				if(this.x>=x&&this.x<=x+64)
					return true;
		return false;	
	}

	public int getY() {
		return y;
	}

	public int getX() {
		return x;
	}

	public void setY(int y) {
		this.y = y;
	}

	public void setX(int x) {
		this.x = x;
	}
}
