package Negocio;

import ValueObjects.DisparoVO;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Enemigo.java
//  @ Date : 05/11/2018
//  @ Author : 
//
//




public class Enemigo {
	
	private int x;
	private int y;
	private boolean estado;
	private Disparo disparo;
	
	public Enemigo(int x, int y) {
		this.x = x;
		this.y = y;
		this.estado=true;
		this.disparo=null;
	}
	
	public DisparoVO disparar(DisparoVO dis) {

		disparo = new Disparo(this.x+25,this.y+40);
		dis.setX(disparo.getX());
		dis.setY(disparo.getY());
		return dis;
	}
	
	public void moverDer() {//Debe recibir un valor posicion.
		this.x+=10;
	}
	public void moverIzq() {//Debe recibir un valor posicion.
		this.x-=10;
	}
	
	public void bajar() {
		this.y+=64;
	}
	
	public boolean soyElEnemigo(int x, int y) {
		return false;
	
	}

	public int getX() {
		return x;
	}

	public int getY() {
		return y;
	}
	
	public void setEstado(boolean e) {
		this.estado=e;
	}
	
	public boolean isEstado() {
		return estado;
	}

	public Disparo getDisparo() {
		return disparo;
	}

	public void setDisparo() {
		this.disparo = null;
	}
	
}
