package Negocio;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jugador.java
//  @ Date : 05/11/2018
//  @ Author : 
//
//




public class Jugador implements Comparable<Jugador> {
	
	private String nombre;
	private int puntaje;
	
	public Jugador(String nombre, int puntaje) {
		this.nombre = nombre;
		this.puntaje = puntaje;
	}
	
	public String getNombre() {
		return nombre;
	}
	
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	public int getPuntaje() {
		return puntaje;
	}
	
	public void setPuntaje(int puntaje) {
		this.puntaje = puntaje;
	}

	@Override
	public int compareTo(Jugador j) {
		
		if(this.puntaje<j.getPuntaje())
			return 1;
		else if (this.puntaje>j.getPuntaje())
			return -1;
		else 
			return 0;
			
	}
}
